version: "3.7"
services: 
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ES_JAVA_OPTS: "-Xms512m -Xmx3000m"
    depends_on:
      - zookeeper
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
      - 6969:6969
    environment: 
      CONSUMER_ENABLED: "true"
      CONSUMER_AUTOCOMMIT: "true"
      CONSUMER_AUTOCOMMIT_INTERVALS: "1000"
      CONSUMER_FETCH_MAX_WAIT: "3000"
      CONSUMER_FROM_OFFSET: "true"
      CONSUMER_TOPIC_NAME: "lior.test"
      CONSUMER_OFFSET: "0"
      CONSUMER_PARTITION: "0"
      KAFKA_HOST: kafka:9092
      KAFKA_SASL_MECHANISM: "PLAIN"
      KAFKA_SECURE_CONNECTION: "false"
      KAFKA_SASL_USER: "xxxx"
      KAFKA_SASL_PASSWORD: "yyyy"
      KAFKA_SSL_CERT_LOCATION: "assets/client.truststore.jks"
    depends_on:
      - kafka
  
  # zookeeper:
  #   container_name: zookeeper
  #   image: confluentinc/cp-zookeeper
  #   ports:
  #     - "32181:32181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 32181
  #     ZOOKEEPER_TICK_TIME: 2000
  #     ZOOKEEPER_SYNC_LIMIT: 2
    
  # kafka:
  #   container_name: kafka
  #   image: confluentinc/cp-kafka
  #   ports:
  #     - "9094:9094"
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
  #     KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     ES_JAVA_OPTS: "-Xms512m -Xmx3000m"
  #   depends_on:
  #     - zookeeper